// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4lwEoc7wk8o8ZauSo-WVQb7emYiBK6Go',
    appId: '1:795446990515:web:1bc32134b65a8b9713c2c6',
    messagingSenderId: '795446990515',
    projectId: 'movieverse-cd97b',
    authDomain: 'movieverse-cd97b.firebaseapp.com',
    storageBucket: 'movieverse-cd97b.firebasestorage.app',
    measurementId: 'G-B0PK6SHFQ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi1fEFHWA4MKKrJBmlgIosvfg8scLu86w',
    appId: '1:795446990515:android:652cac1689b5c1cb13c2c6',
    messagingSenderId: '795446990515',
    projectId: 'movieverse-cd97b',
    storageBucket: 'movieverse-cd97b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA8BgNk-7s0RUxFK18oL-Wh--UjabB96k',
    appId: '1:795446990515:ios:0d2bafb3864274c513c2c6',
    messagingSenderId: '795446990515',
    projectId: 'movieverse-cd97b',
    storageBucket: 'movieverse-cd97b.firebasestorage.app',
    iosBundleId: 'com.example.movieVerse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA8BgNk-7s0RUxFK18oL-Wh--UjabB96k',
    appId: '1:795446990515:ios:0d2bafb3864274c513c2c6',
    messagingSenderId: '795446990515',
    projectId: 'movieverse-cd97b',
    storageBucket: 'movieverse-cd97b.firebasestorage.app',
    iosBundleId: 'com.example.movieVerse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4lwEoc7wk8o8ZauSo-WVQb7emYiBK6Go',
    appId: '1:795446990515:web:81b39bd02ed34e6913c2c6',
    messagingSenderId: '795446990515',
    projectId: 'movieverse-cd97b',
    authDomain: 'movieverse-cd97b.firebaseapp.com',
    storageBucket: 'movieverse-cd97b.firebasestorage.app',
    measurementId: 'G-LQQ4JFZZ9R',
  );
}
