// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKa-SeAGI7u7x2PKeq35Me6wfG7h15XLY',
    appId: '1:222419290639:web:2144c04e0b3838649b317a',
    messagingSenderId: '222419290639',
    projectId: 'movieverse-2beab',
    authDomain: 'movieverse-2beab.firebaseapp.com',
    storageBucket: 'movieverse-2beab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcvVajXNBq7YFXX4VwLQcusqaQXXH4mLU',
    appId: '1:222419290639:android:4c91df7005d0e22f9b317a',
    messagingSenderId: '222419290639',
    projectId: 'movieverse-2beab',
    storageBucket: 'movieverse-2beab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVUZ3YSHcUpoxlWMYIz2RLK-Nmw14Ykjo',
    appId: '1:222419290639:ios:90e04999e60e20989b317a',
    messagingSenderId: '222419290639',
    projectId: 'movieverse-2beab',
    storageBucket: 'movieverse-2beab.firebasestorage.app',
    iosClientId: '222419290639-2f1kpejh623sm40pnftboa9tbie3s8g9.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieVerse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVUZ3YSHcUpoxlWMYIz2RLK-Nmw14Ykjo',
    appId: '1:222419290639:ios:90e04999e60e20989b317a',
    messagingSenderId: '222419290639',
    projectId: 'movieverse-2beab',
    storageBucket: 'movieverse-2beab.firebasestorage.app',
    iosClientId: '222419290639-2f1kpejh623sm40pnftboa9tbie3s8g9.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieVerse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKa-SeAGI7u7x2PKeq35Me6wfG7h15XLY',
    appId: '1:222419290639:web:46c43cfa072305c49b317a',
    messagingSenderId: '222419290639',
    projectId: 'movieverse-2beab',
    authDomain: 'movieverse-2beab.firebaseapp.com',
    storageBucket: 'movieverse-2beab.firebasestorage.app',
  );

}